@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'sales doc'
@Metadata.ignorePropagatedAnnotations: true
define root view entity zmn_c_salesdoc as projection on zmn_salsdoc
{
    @UI.lineItem: [{ position: 10 }]
    key SalesDocument,
    @UI.lineItem: [{ position: 20 }]
    key SalesDocumentItem,
    SalesDocumentItemCategory,
    SalesDocumentItemType,
    IsReturnsItem,
    CompletionRule,
    CreatedByUser,
    CreationDate,
    CreationTime,
    LastChangeDate,
    Division,
        @UI.lineItem: [{ position: 30 }]
    
    Material,
        @UI.lineItem: [{ position: 40 }]
    
    _ProductText[ 1:  Language = 'E'].ProductName,
    Product,
    MaterialByCustomer,
    InternationalArticleNumber,
    Batch,
    ProductHierarchyNode,
    ProductCatalog,
    MaterialSubstitutionReason,
    MaterialGroup,
    ProductGroup,
    @Semantics.quantity.unitOfMeasure: 'OrderQuantityUnit'
        @UI.lineItem: [{ position: 50 }]
    
    OrderQuantity,
    OrderQuantityUnit,
    OrderToBaseQuantityDnmntr,
    OrderToBaseQuantityNmrtr,
    @Semantics.quantity.unitOfMeasure: 'ItemWeightUnit'
    ItemNetWeight,
    ItemWeightUnit,
    @Semantics.quantity.unitOfMeasure: 'ItemVolumeUnit'
    ItemVolume,
    ItemVolumeUnit,
    ServicesRenderedDate,
    SalesDistrict,
    SalesDeal,
    SalesPromotion,
    RetailPromotion,
    CustomerGroup,
    SlsDocIsRlvtForProofOfDeliv,
    SalesDocumentRjcnReason,
    AlternativeToItem,
    ReturnReason,
    ReturnsRefundExtent,
    RetsMgmtProcessingBlock,
    RequirementSegment,
    QuantityIsFixed,
    EquipmentInstallationDate,
    EquipmentDeliveryAccptcDate,
    EquipmentDismantlingDate,
    RequestedCancellationDate,
    SlsContractCanclnReqRcptDate,
    CanclnDocByContrPartner,
    ContractPartnerCanclnDocDate,
    SalesContractCanclnParty,
    SalesContractCanclnReason,
    SalesContractFollowUpAction,
    SlsContractFollowUpActionDate,
    SalesDocumentItemProcgCode,
    PlngDelivSchedInstrn,
     @Semantics.amount.currencyCode: 'TransactionCurrency'
    NetAmount,
    TransactionCurrency,
    PricingReferenceMaterial,
    MaterialPricingGroup,
    ProductTaxClassification1,
    ProductTaxClassification2,
    ProductTaxClassification3,
    ProductTaxClassification4,
    ProductTaxClassification5,
    ProductTaxClassification6,
    ProductTaxClassification7,
    ProductTaxClassification8,
    ProductTaxClassification9,
    MatlAccountAssignmentGroup,
    PricingDate,
    ExchangeRateDate,
    PriceDetnExchangeRate,
     @Semantics.amount.currencyCode: 'TransactionCurrency'
    NetPriceAmount,
    NetPriceQuantity,
    NetPriceQuantityUnit,
    StatisticalValueControl,
     @Semantics.amount.currencyCode: 'TransactionCurrency'
    TaxAmount,
     @Semantics.amount.currencyCode: 'TransactionCurrency'
    CostAmount,
    SalesDocumentCondition,
    MainItemPricingRefProduct,
    CustomerPriceGroup,
    ShippingPoint,
    ShippingType,
    InventorySpecialStockType,
    InventorySpecialStockValnType,
    DeliveryPriority,
    Plant,
    OriginalPlant,
    TransitPlant,
    StorageLocation,
    Route,
    BaseUnit,
    DeliveryGroup,
    DeliveryDateQuantityIsFixed,
    PartialDeliveryIsAllowed,
    MaxNmbrOfPartialDelivery,
    UnlimitedOverdeliveryIsAllowed,
    OverdelivTolrtdLmtRatioInPct,
    UnderdelivTolrtdLmtRatioInPct,
    BatchManagementIsSalesInternal,
    ReceivingPoint,
    ProductSeasonYear,
    ProductSeason,
    ProductCollection,
    ProductTheme,
    FashionCancelDate,
    ProductCharacteristic1,
    ProductCharacteristic2,
    ProductCharacteristic3,
    ShippingGroupNumber,
    ShippingGroupRule,
    ARunPriorityValue,
    ARunDemandGroupPriority,
    BillingDocumentDate,
    ItemIsBillingRelevant,
    ItemBillingBlockReason,
    BillingPlan,
    ReferenceBillingPlan,
    ReferenceBillingPlanItem,
    IncotermsVersion,
    IncotermsClassification,
    IncotermsTransferLocation,
    IncotermsLocation1,
    IncotermsLocation2,
    OrderCombinationIsAllowed,
    CustomerPaymentTerms,
    PaymentMethod,
    FixedValueDate,
    AdditionalValueDays,
    ContractAccount,
    FiscalYear,
    FiscalPeriod,
    CustomerAccountAssignmentGroup,
    BusinessArea,
    ControllingArea,
    OrderID,
    ControllingObject,
    OriginSDDocument,
    OriginSDDocumentItem,
    ReferenceSDDocument,
    ReferenceSDDocumentItem,
    HigherLevelItem,
    ValueContract,
    ValueContractItem,
    BusinessSolutionOrder,
    BusinessSolutionOrderItem,
    CorrespncExternalReference,
    POCorrespncExternalReference,
    CustomerConditionGroup1,
    CustomerConditionGroup2,
    CustomerConditionGroup3,
    CustomerConditionGroup4,
    
    CustomerConditionGroup5,
    SDProcessStatus,
    DeliveryConfirmationStatus,
    DeliveryDateTypeRule,
    PurchaseConfirmationStatus,
    TotalDeliveryStatus,
    DeliveryStatus,
    DeliveryBlockStatus,
    OrderRelatedBillingStatus,
    BillingBlockStatus,
    ItemGeneralIncompletionStatus,
    ItemBillingIncompletionStatus,
    PricingIncompletionStatus,
    ItemDeliveryIncompletionStatus,
    SDDocumentRejectionStatus,
    TotalSDDocReferenceStatus,
    SDDocReferenceStatus,
    ChmlCmplncStatus,
    DangerousGoodsStatus,
    SafetyDataSheetStatus,
    TrdCmplncEmbargoSts,
    TrdCmplncSnctndListChkSts,
    OvrlTrdCmplncLegalCtrlChkSts,
    AltvBsdConfSubstitutionStatus,
    ContractItemDownPaymentStatus,
    ValueChainCategory,
    ServiceDocumentType,
    ServiceDocument,
    ServiceDocumentItem,
    SalesDocumentType,
    _Plant.PlantName,
    SalesOrganization,
    DistributionChannel,
    OrganizationDivision,
    SalesOffice,
    SalesGroup,
        @UI.lineItem: [{ position: 60 }]

    SoldToParty,
        @UI.lineItem: [{ position: 70 }]

    
    _SoldToParty.CustomerName,
    SalesDocumentDate,
    SDDocumentReason,
    RequestedDeliveryDate,
    ShippingCondition,
    ShipToParty,
    PayerParty,
    BillToParty,
    SalesEmployee,
    PlanningMaterial,
    PlanningPlant,
    ProductBaseUnit,
    /* Associations */
    _ControllingArea,
    _CustomerGroup,
    _DistributionChannel,
    _Division,
    _Material,
    _MaterialGroup,
    _MaterialPlant,
    
    _Plant,
    _Product,
    _ProductGroup,
    _ProductHierarchyNode,
    _ProductText,
    _ProductUnit,
    _PurchaseConfirmationStatus,
    _ReferenceSDDocument,
    _ReturnReason,
    _ReturnsRefundExtent,
    _Route,
    _SafetyDataSheetStatus,
    _SalesContractCanclnParty,
    _SalesContractCanclnReason,
    _SalesDeal,
    _SalesDistrict,
    _SalesDocument,
    _SalesDocumentItemProcgCode,
    _SalesDocumentRjcnReason,
    _SalesDocumentType,
    _SalesEmployee,
    _SalesGroup,
    _SalesOffice,
    _SalesOrganization,
    _SalesValueChainCategory,
    _ScheduleLine,
    _ServiceDocumentType,
    _ShippingCondition,
    _ShippingPoint,
    _ShippingPointText,
    _ShippingType,
    _ShipToParty,
    _SlsDocItemEnhancedFields,
    _SoldToParty,
    _SolutionOrder,
    _SolutionOrderItem,
    _StatisticalValueControl,
    _StorageLocation,
    _TotalDeliveryStatus,
    _TotalSDDocReferenceStatus,
    _TransactionCurrency,
    _TransitPlant
}
